
FROM ruby:2.4.2

RUN gem install rails \
  && gem install puma

# Get latest nodejs PPA and other repos
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - \
  && apt-get install -y nodejs \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update -y
RUN apt-get upgrade -y

RUN apt-get install -y yarn

RUN mkdir /var/www \
  && cd /var/www

# clone CALS
RUN git clone -b development https://github.com/ca-cwds/CALS.git /var/www/cals

WORKDIR /var/www/cals

RUN cd /var/www/cals \
  && bundle install \
  && yarn install

# ENV variables
ENV BASE_CALS_API_URL=http://localhost:3001/v1 \
  CALS_API_URL=https://calsapi.preint.cwds.io \
  BASE_SEARCH_API_URL=https://dora.preint.cwds.io \
  GEO_SERVICE_URL=https://geo.preint.cwds.io \
  AUTHENTICATION_API_BASE_URL=https://web.preint.cwds.io/perry \
  USE_XVFB=true


# RUN tests
# RUN rails assets:precompile RAILS_ENV=test
# RUN npm run spec-ci
# RUN npm run karma-ci

# ENV variables
ENV REDIS_HOST=localhost \
  REDIS_PORT=6379 \
  RAILS_RELATIVE_URL_ROOT=/cals

# compile assets
RUN rails assets:precompile RAILS_ENV=development

# run rails server
CMD rails server -e development -b 0.0.0.0 -p 3000
